project:
  type: website
  output-dir: docs

website:
  title: "Luke Yek"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: dataviz.qmd
        text: Data Visualization
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

